project:
  type: website
  output-dir: docs

website:
  title: "Поведение FEM-программ при неопределённости в граничных условиях"
  page-navigation: true
  reader-mode: true
  open-graph: true
  twitter-card:
    image: images/cover.png
  navbar:
    right:
      - href: balka.html
        text: Главная

format:
  html:
    theme: cosmo
    css: styles/styles.css
    toc: true
    toc-location: left
    mainfont: system-ui